### ISSUE TITLE
`Error: ERR wrong number of arguments for 'hmset' command` while indexing

### ISSUE THREAD

**Issue by technicalpickles** [Aupajo/hubot-script-catalog#2]
I just cloned the repo, `bundle install`, then `rake`, and it's all sorts of unhappy about that:

<pre>$ rake
mkdir -p tmp
rm -rf tmp/hubot-scripts
remote: Counting objects: 5592, done.
remote: Compressing objects: 100% (1742/1742), done.
remote: Total 5592 (delta 3085), reused 5401 (delta 2925)
Receiving objects: 100% (5592/5592), 741.26 KiB | 637 KiB/s, done.
Resolving deltas: 100% (3085/3085), done.
Adding 46elks.coffee...Error: ERR wrong number of arguments for 'hmset' command
Adding 9gag.coffee...Error: ERR wrong number of arguments for 'hmset' command
....</pre>

I added some extra logging to see the rest of the trace, and it looks like:

<pre>Adding yuno.coffee...Error: ERR wrong number of arguments for 'hmset' command
/Users/technicalpickles/.rvm/gems/ree-1.8.7-2011.03/gems/redis-2.2.2/lib/redis/client.rb:47:in `call'
/Users/technicalpickles/.rvm/gems/ree-1.8.7-2011.03/gems/redis-2.2.2/lib/redis.rb:744:in `hmset'
/Users/technicalpickles/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/Users/technicalpickles/.rvm/gems/ree-1.8.7-2011.03/gems/redis-2.2.2/lib/redis.rb:743:in `hmset'
/Users/technicalpickles/.rvm/gems/ree-1.8.7-2011.03/gems/redis-namespace-1.1.0/lib/redis/namespace.rb:214:in `send'
/Users/technicalpickles/.rvm/gems/ree-1.8.7-2011.03/gems/redis-namespace-1.1.0/lib/redis/namespace.rb:214:in `method_missing'
Rakefile:39
Rakefile:13:in `each'
Rakefile:13
</pre>

Not sure if it's something about how hmset is being called, or an issue with the redis gem yet.

**Comment by Aupajo** [comment]
Hey. I have a suspicion this might be the version of Ruby you're using. Can you try it with 1.9.3?

It'd be good to get an idea of what's being passed to `hmset`. Try replacing your `Rakefile` with the one in this Gist: https://gist.github.com/3120979

The output should look like:

```
Adding 9gag.coffee...["description", "", "dependencies", "\"htmlparser\": \"1.7.6\"\n\"soupselect: \"0.2.0\"\n", "configuration", "", "commands", "hubot 9gag me - Returns a random meme image\n", "author", "EnriqueVidal \n"]
```

**Comment by Aupajo** [comment]
Hmm. Just tried it on `ree-1.8.7`, and didn't run into problems their either. Try the Gist thing.
