### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by patrickt010** [Aupajo/hubot-script-catalog#3]
Site is not working : /

**Comment by Aupajo** [comment]
Thanks for the heads-up!

There's currently an issue with the Redis server.

Unfortunately, there's not a whole lot I can do but wait for them to fix it.

I have, in the meantime, at least updated the error page to be a bit more descriptive.

Will close this issue when Redis comes back online and service is restored.

**Comment by patrickt010** [comment]
Thanks!

**Comment by Aupajo** [comment]
Up-and-running again now. Thanks again for the heads-up.

**Comment by patrickt010** [comment]
No worries thanks for working on this project!
