### ISSUE TITLE
Feature Request: Create a way of sorting the scripts.

### ISSUE THREAD

**Issue by remybach** [Aupajo/hubot-script-catalog#5]
At the very least by date added would be a huge help.

Unfortunately I'm nowhere near knowledgable enough with ruby otherwise I'd do it and send a PR. :(

**Comment by Aupajo** [comment]
:+1: Thanks for the feature request. I'll take a look into this.

**Comment by remybach** [comment]
Wahey... That was quick! Thanks so much :)

![Woohoo!](https://dl.dropboxusercontent.com/u/2819415/gifs/whose-line-is-it-anyway-celebrate-balloons-woohoo-party.gif)

**Comment by Aupajo** [comment]
Haha, no problem :) This code is in dire need of refactoring, but this will work well enough for the mean time.

:shipit: Just rolled it out now: http://hubot-script-catalog.herokuapp.com/recent

**Comment by Aupajo** [comment]
Ah :( just realised I was sorting by most recently updated rather than by most recent additions. Sorry, it's late here. Have fixed and updated.
